In [1]:
import numpy as np

In [2]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    
    a = np.array(feature_vector)
    b = np.array(current_theta)
    if label*(np.dot(a, b) + current_theta_0) <= 0:
        b = b + label*a
        d = current_theta_0 + label
        e = (b, d)
        return (e)
    else:
        return(current_theta, current_theta_0)

In [47]:
def get_order(n_samples):
    try:
        with open(str(n_samples) + '.txt') as fp:
            line = fp.readline()
            return list(map(int, line.split(',')))
    except FileNotFoundError:
        random.seed(1)
        indices = list(range(n_samples))
        random.shuffle(indices)
        return indices

In [44]:
def perceptron(feature_matrix, labels, T):
    y0 = np.zeros(len(np.transpose(feature_matrix)))
    y1 = 0
    for i in range (0, len(labels)):
        h = feature_matrix[i]
        f = labels[i]
        y1 = y1 + f
        d = perceptron_single_step_update(h, f, y0, y1)
    return (d)
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            # 
            pass

In [45]:
feature_matrix = [[-0.28675906, 0.1454169, -0.25436512, 0.03940796, 0.06992047, -0.09304647,
 -0.28190337, 0.46945007, -0.01767601, -0.37744711],
 [0.09451184, 0.12903728, 0.39961122, 0.38112039, -0.21271596, -0.38842912,
  0.20808818, 0.15552505, -0.42481425, 0.04320615],
 [0.17716892, -0.26139067, -0.41769041, -0.31868409, -0.13644654, 0.45332973,
 -0.27815157, -0.1103787, -0.18549674, 0.20602163],
 [0.48197338, 0.41613507, 0.08671217, 0.15448822, -0.08569795, 0.31240061,
  0.3045447, -0.03076806, -0.15501701, -0.01143934],
 [0.49913154, -0.17041918, 0.36348827, 0.11344561, -0.35578383, -0.09780351,
 -0.09479426, -0.33652134, 0.41637817, 0.47044146]]
labels = [-1, 1, -1, 1, -1]
T = 5

In [46]:
perceptron(feature_matrix, labels, T)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), -1)

In [35]:
b =np.zeros(5)

In [8]:
b

array([0., 0., 0., 0., 0.])

In [12]:
a = np.array([[1,2], [3,4], [5,6]])

In [13]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
c = np.zeros(len(np.transpose(a)))

In [22]:
c

array([0., 0.])

In [24]:
a.size

6

In [25]:
c.size

2

In [26]:
a.shape

(3, 2)

In [27]:
c.shape

(2,)

In [28]:
a[1]

array([3, 4])

In [29]:
e = np.zeros(len(a))

In [30]:
e

array([0., 0., 0.])

In [31]:
e.shape

(3,)