In [1]:
import numpy as np

In [12]:
def hinge_loss_single(feature_vector, label, theta, theta_0):
    a = np.array(theta)
    b = np.array(feature_vector)
    z = label*(np.dot(a, b) + theta_0)
    if z >= 1:
        return (0)
    else:
        return (1-z)

In [139]:
hinge_loss_single([2.54082327, 1.17402711, 6.88766103, 4.98721275, 4.17841889, 1.1948282,
 3.0167242, 9.79815021, 9.14097873, 5.02653342], 1, [2.17878202, 3.71516109, 7.74431053, 2.67725455, 1.61091645, 7.92472113,
 1.42831072, 4.65898466, 6.24269712, 4.70062766], 1)

0

In [266]:
def hinge_loss_full(feature_matrix, labels, theta, theta_0):
    f = np.array(labels)
    h = np.array([feature_matrix])
    r = np.array([theta])
    for i in range(0, f.size):
        a = np.array(hinge_loss_single(h[i,:], f[i], theta, theta_0))
        b = np.sum(a)
        c = b*(1/np.size(f))
        return (c)
    
        
    
    

In [267]:
hinge_loss_full([[2.54082327, 1.17402711, 6.88766103, 4.98721275, 4.17841889, 1.1948282,
 3.0167242, 9.79815021, 9.14097873, 5.02653342], [2.54082327, 1.17402711, 6.88766103, 4.98721275, 4.17841889, 1.1948282,
 3.0167242, 9.79815021, 9.14097873, 5.02653342]], ([1,1]), [2.17878202, 3.71516109, 7.74431053, 2.67725455, 1.61091645, 7.92472113,
 1.42831072, 4.65898466, 6.24269712, 4.70062766], 1)

ValueError: shapes (10,) and (2,10) not aligned: 10 (dim 0) != 2 (dim 0)

In [24]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    a = np.array(feature_vector)
    b = np.array(current_theta)
    if label*(np.dot(a, b) + current_theta_0) <= 0:
        b = b + label*a
        d = current_theta_0 + label
        e = (b, d)
        return (e)
    else:
        return(current_theta, current_theta_0)
    
    
    
    
    
    
    
    

In [258]:
def perceptron(feature_matrix, labels, T):
    a = np.array([feature_matrix])
    b = np.array(labels)
    theta = np.zeros(b.size)
    theta_0 = 0
    for i in range(0, np.size(b)):
        d = perceptron_single_step_update(a[i,:], b[i], theta, theta_0)
        return (d)

In [30]:
def pegasos_single_step_update(
        feature_vector,
        label,
        L,
        eta,
        current_theta,
        current_theta_0):
    a = np.array(feature_vector)
    b = np.array(current_theta)
    if label*(np.dot(a, b) + current_theta_0) <= 1:
        b = b*(1 - L*eta) + eta*label*a
        d = current_theta_0*(1 - eta*L) + eta*label
        return (b, d)
    else:
        b = b*(1 - L*eta)
        d = current_theta_0
        return (b,d)
        

In [31]:
pegasos_single_step_update([-0.20708026, -0.36186563,  0.12818786,  0.34176084, -0.14926241, -0.0079416,
  0.44620129,  0.01082064, -0.41072232, -0.06969495], 1, 0.9852957618190694,0.17153171319038307, [-0.31962095, -0.05471449,  0.02418146,  0.42473018, -0.48736942, -0.36700418,
  0.4586967,  -0.06948516,  0.07891067,  0.01992894], 1.04037579712791)

(array([-0.26560198, -0.04546722,  0.02009456,  0.35294676, -0.40499937,
        -0.304977  ,  0.38117261, -0.05774151,  0.06557402,  0.01656076]),
 1.04037579712791)

In [32]:
1+1

2

In [171]:
h = np.array([[1,2],[3,4],[5,6]])

In [172]:
h

array([[1, 2],
       [3, 4],
       [5, 6]])

In [251]:
h.size

3

In [174]:
h[0,:]

array([1, 2])

In [178]:
v = np.array((1,2,3,4,5))

In [252]:
v.size

5

m = np.zeros(v.size)

In [256]:
n = np.zeros(v.size)

In [257]:
n

array([0., 0., 0., 0., 0.])

In [179]:
v

array([1, 2, 3, 4, 5])

In [180]:
v[2]

3

In [192]:
np.size(v)

5

In [216]:
h[:,0]

array([1, 3, 5])

In [217]:
h[1]

array([3, 4])

In [218]:
h[1,:]

array([3, 4])

In [219]:
g = np.array([[1,2],[3,4],[5,6]])

In [225]:
g[1,:]

array([3, 4])

In [237]:
h = np.array((1, -1, 1))

In [238]:
h[1]

-1

In [239]:
j = np.array((10,11))

In [240]:
k = 5

In [261]:
hinge_loss_full(g, h, j, k)

ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)

In [ ]:
def classify(feature_matrix, theta, theta_0):
    a = np.array([feature_matrix])
    b = np.array(theta)
    for i in range()